# theme: jekyll-theme-merlot
remote_theme: dbtek/dbyll
title: dbyll
disqus: dbyll-ghost # disqus short name
author:  
  name: arnau manyosa  
  email: youremail@mail.com
  github: asd123  
  twitter: asd123  
  pinterest: asd123  
  linkedin: asd123  
  resume: asd123  
  bio: Your stylish,  minimalist theme!  
  email_md5: md5ofemail  
