# User config
author: "Arnau Manyosa-Plaza"
tagline: "Frontend Developer/UIUX Designer"
greeting: "Hi, I'm Arnau."
slogan: "Design is my passion, problem-solving is my attitude."
current_status: "Currently working on a not-named-yet personal project."
previous_status:
  - company_name: "IBM Research"
    company_url: "https://www.research.ibm.com/"
  - company_name: "FLX Labs"
    company_url: "https://www.flxlabs.com"
  - company_name: "Hult Business School"
    company_url: "https://www.hult.edu"
keywords: "Arnau Manyosa-Plaza, Frontend, Front-end, Front end, Developer, UI, UX, Experience, Design, Designer, Happyness, Problem solver"
email: "arnau.manyosa@protonmail.com"
linkedin: "https://www.linkedin.com/in/arnaumanyosa/"
github: "https://github.com/arnaumanyosa/"
dribbble: "https://dribbble.com/amplified/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed