# theme: jekyll-theme-cayman
# remote_theme: volny/creative-theme-jekyll
remote_theme: joshgerdes/jekyll-uno
title: Arnau Manyosa-plaza
description: Front-end Dev + UX Designer

theme: jekyll-theme-minimal