# site settings
title: Arnau Manyosa-Plaza
subtitle: Frontend Dev + UX Designer
email: arnau.manyosa@protonmail.com
description: With a technological soul and artistic brain, <br />I aim to create beautiful digital experiences.
baseurl: "/" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author: Arnau Manyosa-Plaza

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
github_url: https://github.com/arnaumanyosa/
linkedin_url: https://www.linkedin.com/in/arnaumanyosa/
twitter_url: https://twitter.com/arnaumanyosa

# build settings
markdown: kramdown

sass:
  style: compressed
